"""crear tabla detallereclamo proveedor

Revision ID: 05bc41bce071
Revises: 62e6c910bec6
Create Date: 2026-09-27 12:17:11.499254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bc41bce071'
down_revision = '62e6c910bec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReclamoProveedor',
    sa.Column('idReclamoProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idPedidoProveedor', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidadAfectada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('En proceso', 'Resuelto', 'Rechazado')", name='ck_estado_reclamo_proveedor'),
    sa.ForeignKeyConstraint(['idPedidoProveedor'], ['pedido_proveedor.idPedidoProveedor'], ),
    sa.PrimaryKeyConstraint('idReclamoProveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReclamoProveedor')
    # ### end Alembic commands ###
