"""se agrego la fk de sucursal a inventario

Revision ID: 0f92f989670d
Revises: 1faead030fc1
Create Date: 2026-09-28 19:02:00.938207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f92f989670d'
down_revision = '1faead030fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idSucursal', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sucursales', ['idSucursal'], ['idSucursal'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventario', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idSucursal')

    # ### end Alembic commands ###
