"""crear tabla proveedor

Revision ID: 1710a33763fb
Revises: 6f01b2e59024
Create Date: 2026-09-27 11:20:21.720746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1710a33763fb'
down_revision = '6f01b2e59024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Proveedor',
    sa.Column('idProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreEmpresa', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idProveedor'),
    sa.UniqueConstraint('nit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Proveedor')
    # ### end Alembic commands ###
