"""crear tabla SucursalUsuario

Revision ID: 19079a7c66b4
Revises: b47454086c65
Create Date: 2026-09-26 15:37:44.476917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19079a7c66b4'
down_revision = 'b47454086c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SucursalUsuario',
    sa.Column('idSucursalUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idSucursalUsuario'),
    sa.UniqueConstraint('idSucursal', 'idUsuario', name='uq_sucursal_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SucursalUsuario')
    # ### end Alembic commands ###
