"""crear la tabla Cliente

Revision ID: 1b96132b1314
Revises: 89b88bf7ed09
Create Date: 2026-09-26 22:21:29.079253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b96132b1314'
down_revision = '89b88bf7ed09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('idCliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idTipoDocumento', sa.Integer(), nullable=False),
    sa.Column('numeroDocumento', sa.String(length=20), nullable=False),
    sa.Column('primerNombre', sa.String(length=150), nullable=False),
    sa.Column('segundoNombre', sa.String(length=150), nullable=True),
    sa.Column('primerApellido', sa.String(length=150), nullable=False),
    sa.Column('segundoApellido', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correoElectronico', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idTipoDocumento'], ['TipoDeDocumento.idTipoDocumento'], ),
    sa.PrimaryKeyConstraint('idCliente'),
    sa.UniqueConstraint('numeroDocumento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cliente')
    # ### end Alembic commands ###
