"""crear tabla transaccion inventario

Revision ID: 1faead030fc1
Revises: 3e70516f0b49
Create Date: 2026-09-27 13:20:01.706629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1faead030fc1'
down_revision = '3e70516f0b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TransaccionInventario',
    sa.Column('idTransaccionInventario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('idTipoMovimiento', sa.Integer(), nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=True),
    sa.Column('idDevolucion', sa.Integer(), nullable=True),
    sa.Column('idPedidoProveedor', sa.Integer(), nullable=True),
    sa.Column('idAjusteInventario', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('("idVenta" IS NOT NULL)::int + ("idDevolucion" IS NOT NULL)::int + ("idPedidoProveedor" IS NOT NULL)::int + ("idAjusteInventario" IS NOT NULL)::int = 1', name='ck_un_solo_origen'),
    sa.ForeignKeyConstraint(['idAjusteInventario'], ['AjusteInventario.idAjusteInventario'], ),
    sa.ForeignKeyConstraint(['idDevolucion'], ['devolucion.idDevolucion'], ),
    sa.ForeignKeyConstraint(['idInventario'], ['Inventario.idInventario'], ),
    sa.ForeignKeyConstraint(['idPedidoProveedor'], ['pedido_proveedor.idPedidoProveedor'], ),
    sa.ForeignKeyConstraint(['idTipoMovimiento'], ['tipo_movimiento.idTipoMovimiento'], ),
    sa.ForeignKeyConstraint(['idVenta'], ['Venta.idVenta'], ),
    sa.PrimaryKeyConstraint('idTransaccionInventario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TransaccionInventario')
    # ### end Alembic commands ###
