"""arreglo tabla tipo de documento

Revision ID: 39a311628d3f
Revises: 4be5077923f4
Create Date: 2026-09-24 14:19:11.556017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a311628d3f'
down_revision = '4be5077923f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TipoDeDocumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Acronimo', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['Acronimo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TipoDeDocumento', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Acronimo')

    # ### end Alembic commands ###
