"""crear tabla detalle devolucion

Revision ID: 3e70516f0b49
Revises: 4ce9a53879bf
Create Date: 2026-09-27 12:45:39.176728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e70516f0b49'
down_revision = '4ce9a53879bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetalleDevolucion',
    sa.Column('idDetalleDevolucion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idDevolucion', sa.Integer(), nullable=False),
    sa.Column('idDetalleVenta', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidadDevuelta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('productoApto', sa.Boolean(), nullable=False),
    sa.Column('montoDevuelto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idDetalleVenta'], ['detalle_venta.idDetalleVenta'], ),
    sa.ForeignKeyConstraint(['idDevolucion'], ['devolucion.idDevolucion'], ),
    sa.ForeignKeyConstraint(['idProducto'], ['Producto.idProducto'], ),
    sa.PrimaryKeyConstraint('idDetalleDevolucion'),
    sa.UniqueConstraint('idDetalleVenta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DetalleDevolucion')
    # ### end Alembic commands ###
