"""crear tabla tipo de documento

Revision ID: 4be5077923f4
Revises: ab5cf87beb8b
Create Date: 2026-09-24 13:50:30.676977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be5077923f4'
down_revision = 'ab5cf87beb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TipoDeDocumento',
    sa.Column('idTipoDocumento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idTipoDocumento'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TipoDeDocumento')
    # ### end Alembic commands ###
