"""crear tabla devolucion

Revision ID: 4ce9a53879bf
Revises: 5b033f294b5b
Create Date: 2026-09-27 12:38:45.151785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce9a53879bf'
down_revision = '5b033f294b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucion',
    sa.Column('idDevolucion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idFactura', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idTipoDevolucion', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('montoTotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aprobada', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idFactura'], ['Factura.idFactura'], ),
    sa.ForeignKeyConstraint(['idTipoDevolucion'], ['tipo_devolucion.idTipoDevolucion'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idDevolucion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devolucion')
    # ### end Alembic commands ###
