"""crear tabla tipo devolucion

Revision ID: 5b033f294b5b
Revises: 05bc41bce071
Create Date: 2026-09-27 12:21:17.766709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b033f294b5b'
down_revision = '05bc41bce071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_devolucion',
    sa.Column('idTipoDevolucion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idTipoDevolucion'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_devolucion')
    # ### end Alembic commands ###
