"""crear tabla detalle orden proveedor

Revision ID: 62e6c910bec6
Revises: 7b2b01fcdec0
Create Date: 2026-09-27 12:03:13.860057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62e6c910bec6'
down_revision = '7b2b01fcdec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_proveedor',
    sa.Column('idPedidoProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProveedor', sa.Integer(), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idEstadoPedidoProveedor', sa.Integer(), nullable=False),
    sa.Column('fechaPedido', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechaRecepcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idEstadoPedidoProveedor'], ['estado_pedido_proveedor.idEstadoPedidoProveedor'], ),
    sa.ForeignKeyConstraint(['idProveedor'], ['Proveedor.idProveedor'], ),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPedidoProveedor')
    )
    op.drop_table('pedio_proveedor')
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    op.create_table('pedio_proveedor',
    sa.Column('idPedidoProveedor', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idProveedor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idSucursal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idUsuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idEstadoPedidoProveedor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fechaPedido', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fechaRecepcion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idEstadoPedidoProveedor'], ['estado_pedido_proveedor.idEstadoPedidoProveedor'], name=op.f('pedio_proveedor_idEstadoPedidoProveedor_fkey')),
    sa.ForeignKeyConstraint(['idProveedor'], ['Proveedor.idProveedor'], name=op.f('pedio_proveedor_idProveedor_fkey')),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], name=op.f('pedio_proveedor_idSucursal_fkey')),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], name=op.f('pedio_proveedor_idUsuario_fkey')),
    sa.PrimaryKeyConstraint('idPedidoProveedor', name=op.f('pedio_proveedor_pkey'))
    )
    op.drop_table('pedido_proveedor')
    # ### end Alembic commands ###
