"""crear tabla domicilio

Revision ID: 6f01b2e59024
Revises: c3bc4b5eb801
Create Date: 2026-09-27 10:57:45.757351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f01b2e59024'
down_revision = 'c3bc4b5eb801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Domicilio',
    sa.Column('idDomicilio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEntrega', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('horaSalida', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horaRecepcionPago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('montoEsperado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montoRecibido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desbalance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idEntrega'], ['Entrega.idEntrega'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idDomicilio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Domicilio')
    # ### end Alembic commands ###
