"""crear tablas estado pedido proveedor y pedido proveedor, tambien correciones de relaciones

Revision ID: 7b2b01fcdec0
Revises: 1710a33763fb
Create Date: 2026-09-27 11:42:00.497696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2b01fcdec0'
down_revision = '1710a33763fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_pedido_proveedor',
    sa.Column('idEstadoPedidoProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idEstadoPedidoProveedor'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pedio_proveedor',
    sa.Column('idPedidoProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProveedor', sa.Integer(), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idEstadoPedidoProveedor', sa.Integer(), nullable=False),
    sa.Column('fechaPedido', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechaRecepcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idEstadoPedidoProveedor'], ['estado_pedido_proveedor.idEstadoPedidoProveedor'], ),
    sa.ForeignKeyConstraint(['idProveedor'], ['Proveedor.idProveedor'], ),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPedidoProveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedio_proveedor')
    op.drop_table('estado_pedido_proveedor')
    # ### end Alembic commands ###
