"""crear tablas ajuste de inventario y tipo de movimiento

Revision ID: 8434332dc401
Revises: f65f844b47c2
Create Date: 2026-09-26 21:51:48.000009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8434332dc401'
down_revision = 'f65f844b47c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_movimiento',
    sa.Column('idTipoMovimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idTipoMovimiento'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_movimiento')
    # ### end Alembic commands ###
