"""crear tablas ajuste de inventario

Revision ID: 89b88bf7ed09
Revises: 8434332dc401
Create Date: 2026-09-26 21:57:54.103822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b88bf7ed09'
down_revision = '8434332dc401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AjusteInventario',
    sa.Column('idAjusteInventario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idInventario', sa.Integer(), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('idTipoMovimiento', sa.Integer(), nullable=False),
    sa.Column('cantidadAjustada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stockAnterior', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stockNuevo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valorRestado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('estadoAutorizacion', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idInventario'], ['Inventario.idInventario'], ),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.ForeignKeyConstraint(['idTipoMovimiento'], ['tipo_movimiento.idTipoMovimiento'], ),
    sa.ForeignKeyConstraint(['idUser'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idAjusteInventario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AjusteInventario')
    # ### end Alembic commands ###
