"""crear tabla sucursal

Revision ID: a38dd2092b60
Revises: e451c37fb316
Create Date: 2026-09-26 11:56:34.394586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38dd2092b60'
down_revision = 'e451c37fb316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
