"""crear tabla funcion

Revision ID: a9f12e7e6dbd
Revises: 60d3e5a113cf
Create Date: 2026-09-26 11:28:53.326330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f12e7e6dbd'
down_revision = '60d3e5a113cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Funcion',
    sa.Column('idFuncion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modulo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idFuncion'),
    sa.UniqueConstraint('modulo'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Funcion')
    # ### end Alembic commands ###
