"""crear tablas sucursales y usuarios

Revision ID: ab5cf87beb8b
Revises: 
Create Date: 2026-09-24 10:30:03.706278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5cf87beb8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursales',
    sa.Column('idSucursal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreSucursal', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idSucursal'),
    sa.UniqueConstraint('nombreSucursal')
    )
    op.create_table('usuarios',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('sucursales')
    # ### end Alembic commands ###
