"""crear tabla usuario

Revision ID: b47454086c65
Revises: a38dd2092b60
Create Date: 2026-09-26 13:26:26.403064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47454086c65'
down_revision = 'a38dd2092b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idTipoDocumento', sa.Integer(), nullable=False),
    sa.Column('numeroDocumento', sa.String(length=20), nullable=False),
    sa.Column('primerNombre', sa.String(length=150), nullable=False),
    sa.Column('segundoNombre', sa.String(length=150), nullable=True),
    sa.Column('primerApellido', sa.String(length=150), nullable=False),
    sa.Column('segundoApellido', sa.String(length=150), nullable=True),
    sa.Column('correoElectronico', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('idTipoUsuario', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idTipoDocumento'], ['TipoDeDocumento.idTipoDocumento'], ),
    sa.ForeignKeyConstraint(['idTipoUsuario'], ['TipoUsuario.idTipoUsuario'], ),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correoElectronico'),
    sa.UniqueConstraint('numeroDocumento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
