"""crear tabla venta

Revision ID: b91c791ee10e
Revises: c912b211058e
Create Date: 2026-09-27 10:45:44.845890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91c791ee10e'
down_revision = 'c912b211058e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Factura',
    sa.Column('idFactura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('numeroFactura', sa.String(length=50), nullable=False),
    sa.Column('fechaEmision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valorTotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idVenta'], ['Venta.idVenta'], ),
    sa.PrimaryKeyConstraint('idFactura')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Factura')
    # ### end Alembic commands ###
