"""crear tablas producto y unidad producto

Revision ID: b9bccb2daef1
Revises: 16aabc7fa796
Create Date: 2026-09-26 19:32:26.232801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bccb2daef1'
down_revision = '16aabc7fa796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UnidadMedida',
    sa.Column('idUnidadMedida', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=True),
    sa.Column('permite_decimales', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idUnidadMedida'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Producto',
    sa.Column('idProducto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idTipoProducto', sa.Integer(), nullable=False),
    sa.Column('idUnidadMedida', sa.Integer(), nullable=False),
    sa.Column('codigoSKU', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costoUnitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stockMinimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idTipoProducto'], ['TipoProducto.idTipoProducto'], ),
    sa.ForeignKeyConstraint(['idUnidadMedida'], ['UnidadMedida.idUnidadMedida'], ),
    sa.PrimaryKeyConstraint('idProducto'),
    sa.UniqueConstraint('codigoSKU')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Producto')
    op.drop_table('UnidadMedida')
    # ### end Alembic commands ###
