"""crear tabla entrega

Revision ID: c3bc4b5eb801
Revises: b91c791ee10e
Create Date: 2026-09-27 10:51:35.608010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bc4b5eb801'
down_revision = 'b91c791ee10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Entrega',
    sa.Column('idEntrega', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('direccionEntrega', sa.String(length=200), nullable=False),
    sa.Column('costoEnvio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fechaSolicitud', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idVenta'], ['Venta.idVenta'], ),
    sa.PrimaryKeyConstraint('idEntrega')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Entrega')
    # ### end Alembic commands ###
