"""crear tabla detalle de la venta

Revision ID: c912b211058e
Revises: fa94bb32f790
Create Date: 2026-09-27 00:03:40.998424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c912b211058e'
down_revision = 'fa94bb32f790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_venta',
    sa.Column('idDetalleVenta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['Producto.idProducto'], ),
    sa.ForeignKeyConstraint(['idVenta'], ['Venta.idVenta'], ),
    sa.PrimaryKeyConstraint('idDetalleVenta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    # ### end Alembic commands ###
