"""crear tabla usuario_tipo_funcion

Revision ID: e451c37fb316
Revises: a9f12e7e6dbd
Create Date: 2026-09-26 11:45:14.911440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e451c37fb316'
down_revision = 'a9f12e7e6dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_usuario_funcion',
    sa.Column('idTipoUsuarioFuncion', sa.Integer(), nullable=False),
    sa.Column('idTipoUsuario', sa.Integer(), nullable=False),
    sa.Column('idFuncion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idFuncion'], ['Funcion.idFuncion'], ),
    sa.ForeignKeyConstraint(['idTipoUsuario'], ['TipoUsuario.idTipoUsuario'], ),
    sa.PrimaryKeyConstraint('idTipoUsuarioFuncion'),
    sa.UniqueConstraint('idTipoUsuario', 'idFuncion', name='uq_tipo_usuario_funcion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_usuario_funcion')
    # ### end Alembic commands ###
