"""crear tabla mercancia danada y tipo danio

Revision ID: ee0d17163ae9
Revises: 0f92f989670d
Create Date: 2026-10-04 18:07:43.084220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee0d17163ae9'
down_revision = '0f92f989670d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_danio',
    sa.Column('idTipoDanio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('imputableProveedor', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idTipoDanio'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('mercancia_danada',
    sa.Column('idMercanciaDanada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idTipoDanio', sa.Integer(), nullable=False),
    sa.Column('idPedidoProveedor', sa.Integer(), nullable=True),
    sa.Column('idReclamoProveedor', sa.Integer(), nullable=True),
    sa.Column('idAjusteInventario', sa.Integer(), nullable=True),
    sa.Column('idAjusteReversion', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costoUnitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valorPerdida', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('Registrada', 'Dada de baja', 'Reclamada', 'Recuperada', 'Anulada')", name='ck_estado_mercancia_danada'),
    sa.CheckConstraint('cantidad > 0', name='ck_cantidad_mercancia_danada'),
    sa.CheckConstraint('"costoUnitario" >= 0', name='ck_costo_mercancia_danada'),
    sa.CheckConstraint('"valorPerdida" >= 0', name='ck_valor_mercancia_danada'),
    sa.ForeignKeyConstraint(['idAjusteInventario'], ['AjusteInventario.idAjusteInventario'], ),
    sa.ForeignKeyConstraint(['idAjusteReversion'], ['AjusteInventario.idAjusteInventario'], ),
    sa.ForeignKeyConstraint(['idPedidoProveedor'], ['pedido_proveedor.idPedidoProveedor'], ),
    sa.ForeignKeyConstraint(['idProducto'], ['Producto.idProducto'], ),
    sa.ForeignKeyConstraint(['idReclamoProveedor'], ['ReclamoProveedor.idReclamoProveedor'], ),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.ForeignKeyConstraint(['idTipoDanio'], ['tipo_danio.idTipoDanio'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idMercanciaDanada'),
    sa.UniqueConstraint('idAjusteInventario'),
    sa.UniqueConstraint('idAjusteReversion')
    )
    with op.batch_alter_table('mercancia_danada', schema=None) as batch_op:
        batch_op.create_index('ix_mercancia_danada_producto', ['idProducto'], unique=False)
        batch_op.create_index('ix_mercancia_danada_sucursal_fecha', ['idSucursal', 'fecha'], unique=False)

    with op.batch_alter_table('AlertaInventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_alerta_activa'), postgresql_where="((estado)::text <> 'Resuelta'::text)")

    op.drop_table('AlertaInventario')
    with op.batch_alter_table('Factura', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_factura_numero'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_factura_venta'), type_='unique')

    with op.batch_alter_table('Inventario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_inventario_producto_sucursal'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_inventario_producto_sucursal'), ['idProducto', 'idSucursal'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('Factura', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_factura_venta'), ['idVenta'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_factura_numero'), ['numeroFactura'], postgresql_nulls_not_distinct=False)

    op.create_table('AlertaInventario',
    sa.Column('idAlertaInventario', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('idInventario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidadActual', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'No leída'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado::text = ANY (ARRAY['No leída'::character varying, 'Leída'::character varying, 'Resuelta'::character varying]::text[])", name=op.f('AlertaInventario_estado_check')),
    sa.ForeignKeyConstraint(['idInventario'], ['Inventario.idInventario'], name=op.f('AlertaInventario_idInventario_fkey')),
    sa.PrimaryKeyConstraint('idAlertaInventario', name=op.f('AlertaInventario_pkey'))
    )
    with op.batch_alter_table('AlertaInventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_alerta_activa'), ['idInventario'], unique=True, postgresql_where="((estado)::text <> 'Resuelta'::text)")

    with op.batch_alter_table('mercancia_danada', schema=None) as batch_op:
        batch_op.drop_index('ix_mercancia_danada_sucursal_fecha')
        batch_op.drop_index('ix_mercancia_danada_producto')

    op.drop_table('mercancia_danada')
    op.drop_table('tipo_danio')
    # ### end Alembic commands ###
