"""crear tabla inventario

Revision ID: f65f844b47c2
Revises: b9bccb2daef1
Create Date: 2026-09-26 19:47:44.894437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65f844b47c2'
down_revision = 'b9bccb2daef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Inventario',
    sa.Column('idInventario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CantidadDisponible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['Producto.idProducto'], ),
    sa.PrimaryKeyConstraint('idInventario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inventario')
    # ### end Alembic commands ###
