"""crear tabla venta

Revision ID: fa94bb32f790
Revises: 5b98992d1a14
Create Date: 2026-09-26 23:55:58.299673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa94bb32f790'
down_revision = '5b98992d1a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venta',
    sa.Column('idVenta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.Column('idTipoVenta', sa.Integer(), nullable=False),
    sa.Column('idMetodoPago', sa.Integer(), nullable=False),
    sa.Column('fechaHora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuentoTotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['Cliente.idCliente'], ),
    sa.ForeignKeyConstraint(['idMetodoPago'], ['metodo_pago.idMetodoPago'], ),
    sa.ForeignKeyConstraint(['idSucursal'], ['sucursales.idSucursal'], ),
    sa.ForeignKeyConstraint(['idTipoVenta'], ['TipoVenta.idTipoVenta'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.idUsuario'], ),
    sa.PrimaryKeyConstraint('idVenta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Venta')
    # ### end Alembic commands ###
